trigger:
- master

pool:
  name: MyAgentPool
  demands:
   - agent.name -equals nuc

steps:
- task: SynopsysDetectTask@6
  inputs:
    BlackDuckService: 'Testing.BlackDuck'
    DetectVersion: 'latest'
    DetectArguments: '--detect.project.name=MJ-insecure-bank'
- task: CmdLine@2
  displayName: 'Coverity Capture'
  inputs:
    script: 'coverity capture'

- task: CmdLine@2
  displayName: 'Coverity Analysis'
  inputs:
    script: 'coverity analyze'


