name: Black Duck Scan
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  security:
    name: security scans
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: Run Synopsys Detect Rapid Scan
      if: ${{github.event_name == 'pull_request'}}
      uses: synopsys-sig/detect-action@v0.3.0
      with:
          scan-mode: RAPID
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}

    - name: Run Synopsys Detect Intelligent Scan
      if: ${{github.event_name == 'push'}}
      uses: synopsys-sig/detect-action@v0.3.0
      with:
          scan-mode: INTELLIGENT
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 7.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
