name: Coverity

on:
  workflow_dispatch:
jobs:
  scan:
    runs-on: self-hosted
    env:
      COVERITY_TOOL_HOME: 'C:\\usr\\coverity\\cov-analysis-win64-2021.12.1'
    steps:
      #- uses: actions/checkout@v2

      - name: Run a one-line script
        run: |
          echo ${{ env.COVERITY_TOOL_HOME }}
          #$COVERITY_TOOL_HOME\\bin\\cov-build --ident
          #mvn clean package -DskipTests
          

      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
