name: container
on: 
  push:
   branches: [ master ]

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:14.16
      env:
        NODE_ENV: development
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
    steps:
         - name: build insecure bank
           run: |
              bash <(curl -s https://detect.synopsys.com/detect8.sh) --blackduck.url=https://poc389.blackduck.synopsys.com --blackduck.api.token=ZjdkYzdkMzQtMmQ3OS00YmE4LTgyMDEtYTU2NDhlYmQwYzVlOmQ5MmVhNmU5LTZjNjEtNDE4Yy1iZWEwLWVlMDcwZTFhZmM1Yw== --blackduck.trust.cert=true --detect.tools=DETECTOR,SIGNATURE_SCAN,IAC_SCAN
