# Polaris on a self-hosted runner
name: polaris

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  polaris:
    runs-on: ubuntu-latest

    env:
      POLARIS_SERVER_URL: ${{ secrets.POLARIS_URL }}
      POLARIS_ACCESS_TOKEN: ${{ secrets.POLARIS_TOKEN }}
      PROJECT: ${scm.git.repo}
      BLDCMD: mvn -B compile

    steps:
    - uses: AutoModality/action-clean@v1
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Polaris Scan
      run: |
        /opt/polaris/bin/polaris analyze -w -- $BLDCMD
